version: "3"
services:
  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
      - "19999:19999"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./src/main/config/alibaba-rsocket-brokers.json:/etc/prometheus/alibaba-rsocket-brokers.json
      - ./src/main/config/alibaba-rsocket-apps.json:/etc/prometheus/alibaba-rsocket-apps.json