global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'alibaba-rsocket-brokers'
    file_sd_configs:
      - files:
        # http://localhost:9998/metrics/prometheus/broker/targets
        - '/etc/prometheus/alibaba-rsocket-brokers.json'
  - job_name: 'alibaba-rsocket-apps'
    file_sd_configs:
      - files:
        # http://localhost:9998/metrics/prometheus/app/targets
        - '/etc/prometheus/alibaba-rsocket-apps.json'
